spring.application.name=accountserviceproject
server.port=28852
spring.datasource.url=jdbc:h2:file:../service_db
server.error.include-message=always
spring.jpa.hibernate.ddl-auto=update
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/service.p12
server.ssl.key-store-password=service
server.ssl.key-alias=accountant_service
